### ISSUE TITLE
The time type in squbs should be consistent across all APIs 

### ISSUE THREAD

**Issue by sebady** [paypal/squbs#694]

**Comment by sebady** [comment]
We use both TimeUnit and Duration in various APIs.  We should be consistent here.

**Comment by jiminhsieh** [comment]
I noticed that `TimeUnit` is only used at Java API.
https://github.com/paypal/squbs/blob/629803efdd1937f14057a93f39884281063b7c57/squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala#L117-L123
https://github.com/paypal/squbs/blob/629803efdd1937f14057a93f39884281063b7c57/squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala#L133-L141
https://github.com/paypal/squbs/blob/629803efdd1937f14057a93f39884281063b7c57/squbs-unicomplex/src/main/scala/org/squbs/lifecycle/GracefulStopHelper.scala#L146-L153

Since we need to consider Java developers, my idea is `java.time.Duration` for Java APIs and `scala.concurrent.duration.Duration` for Scala APIs.

**Comment by sebady** [comment]
This sounds like a good idea to me.

**Comment by akara** [comment]
I think we're pretty consistent on the Scala `Duration`, but all over the place for the Java time. So this change really focuses on the Java API.

**Comment by jiminhsieh** [comment]
I noticed that some of Java APIs are used `scala.concurrent.duration.FiniteDuration`. I think it was not friendly for Java developers. They will need to import scala std library.
For example: 
https://github.com/paypal/squbs/blob/629803efdd1937f14057a93f39884281063b7c57/squbs-ext/src/main/scala/org/squbs/streams/circuitbreaker/impl/AtomicCircuitBreakerState.scala#L96-L116
https://github.com/paypal/squbs/blob/629803efdd1937f14057a93f39884281063b7c57/squbs-pattern/src/main/scala/org/squbs/pattern/timeoutpolicy/TimeoutPolicy.scala#L275-L279

My question is should we fix those APIs? If yes, should we fix with different PRs?

**Comment by crankydillo** [comment]
@jiminhsieh It seems like that would fall under the scope of making a consistent experience for Java and Scala, so my vote is they should be fixed under the same PR that addresses this issue.  Is there some reason you think they may need a separate PR?

Anyhow, are you interested in working on this?  We're debating this being a part of the 0.12.0 release and are considering picking it up soon; however, we'd love to have a contribution here:)

**Comment by jiminhsieh** [comment]
@crankydillo Yeah, I am interested in this one. I will send a PR later.:)
